version: "3.7"
services:
    heartbeat-controller:
        build:
            context: ./
            dockerfile: Dockerfile.dev
        image: hbv2controller
        container_name: hbv2controller
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            -   .:/var/www/html
        networks:
            - hbv2

    heartbeat-user:
        build:
            context: ./hbv2-user/
            dockerfile: Dockerfile.dev
        image: hbv2user
        container_name: hbv2user
        restart: unless-stopped
        ports:
            - 8081:80
        volumes:
            - ./hbv2-user/:/var/www/html
        networks:
            - hbv2

networks:
    hbv2:
        driver: bridge
